### ISSUE TITLE
Falling edge of clock

### ISSUE THREAD

**Issue by MATRIX7878** [nand2mario/ddr3-tang-primer-20k#2]
Hello,

     After reviewing the code, I see that the code does not deal with falling edges, not taking full use of DDR.  Unless I am missing the negedge calling, is this code capable of using both posedge and negedge?

Thank you

**Comment by nand2mario** [comment]
DDR transmission is done with Gowin serdes primitives (OSER8_MEM and OSER8), at the end of ddr3_controller.v.

**Comment by MATRIX7878** [comment]
Ah.  Ok.  Was not sure if those were truly for both rising and falling edges.  Now that I looked at the documentation (which I should have done to begin with), I see.  Thank you.  The DDR3 algorithm itself is only for rising edge on chip, but data is transferred at both edges.
